var CONSTANTS = {
    REGISTER_REQUEST: 'REGISTER_REQUEST',
    REGISTER_SUCCESS: 'REGISTER_SUCCESS',
    REGISTER_FAILURE: 'REGISTER_FAILURE',

    LOGIN_REQURST: 'LOGIN_REQUEST',
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    LOGIN_FAILURE: 'LOGIN_FAILURE',

    LOGOUT: "LOGOUT",

    TOKEN_CHECK_FAILURE: 'TOKEN_CHECK_FAILURE',


    USER_GET_REQUEST: 'USER_GET_REQUEST',
    USER_GET_SUCCESS: 'USER_GET_SUCCESS',
    USER_GET_FAILURE: 'USER_GET_FAILURE',


    DATA_GET_REQUEST: 'DATA_GET_REQUEST',
    DATA_GET_SUCCESS: 'DATA_GET_SUCCESS',
    DATA_GET_FAILURE: 'DATA_GET_FAILURE',

    DATA_EDITING: 'DATA_EDITING',

    DATA_UPDATE_REQUEST: 'DATA_UPDATE_REQUEST',
    DATA_UPDATE_SUCCESS: 'DATA_UPDATE_SUCCESS',
    DATA_UPDATE_FAILURE: 'DATA_UPDATE_FAILURE',

    DATA_REMOVE_REQUEST: 'DATA_REMOVE_REQUEST',
    DATA_REMOVE_SUCCESS: 'DATA_REMOVE_SUCCESS',
    DATA_REMOVE_FAILURE: 'DATA_REMOVE_FAILURE',

    DATA_CREATE_REQUEST: 'DATA_CREATE_REQUEST',
    DATA_CREATE_SUCCESS: 'DATA_CREATE_SUCCESS',
    DATA_CREATE_FAILURE: 'DATA_CREATE_FAILURE',


    ALERT_CLEAR: 'ALERT_CLEAR',
    ALERT_SUCCESS: 'ALERT_SUCCESS',
    ALERT_FAILURE:'ALERT_FAILURE'
};

export default CONSTANTS