var CONSTANTS = {
    REGISTER_REQUEST: 'REGISTER_REQUEST',
    REGISTER_SUCCESS: 'REGISTER_SUCCESS',
    REGISTER_FAILURE: 'REGISTER_FAILURE',

    LOGIN_REQURST: 'LOGIN_REQUEST',
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    LOGIN_FAILURE: 'LOGIN_FAILURE',
    
    DATA_GET_REQUEST: 'DATA_GET_REQUEST',
    DATA_GET_SUCCESS: 'DATA_GET_SUCCESS',
    DATA_GET_FAILURE: 'DATA_GET_FAILURE',

    DATA_UPDATE_REQUEST: 'DATA_UPDATE_REQUEST',
    DATA_UPDATE_SUCCESS: 'DATA_UPDATE_SUCCESS',
    DATA_UPDATE_FAILURE: 'DATA_UPDATE_FAILURE',

    DATA_REMOVE_REQUEST: 'DATA_REMOVE_REQUEST',
    DATA_REMOVE_SUCCESS: 'DATA_REMOVE_SUCCESS',
    DATA_REMOVE_FAILURE: 'DATA_REMOVE_FAILURE',

    DATA_CREATE_REQUEST: 'DATA_CREATE_REQUEST',
    DATA_CREATE_SUCCESS: 'DATA_CREATE_SUCCESS',
    DATA_CREATE_FAILURE: 'DATA_CREATE_FAILURE',
};

export default CONSTANTS