apiVersion: v1
kind: Service
metadata:
  name: linqh-backend
spec:
  selector:
    app: linqh-backend
  ports:
    - protocol: TCP
      port: 3001
      targetPort: 3001
      nodePort: 31001
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: linqh-backend
  labels:
    app: linqh-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: linqh-backend
  template:
    metadata:
      labels:
        app: linqh-backend
    spec:
      containers:
        - name: linqh-backend
          image: cnlinqh/fullstack.backend 
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3001
          env:
            - name: MONGO_URL
              value: mongodb://root:Sybase123@linqh-mongo:27017/app?authSource=admin

