apiVersion: v1
kind: Secret
metadata:
  name: linqh-mongo-auth
  namespace: default
type: Opaque
data:
  password: U3liYXNlMTIz
---
apiVersion: v1
kind: Service
metadata:
  name: linqh-mongo
spec:
  selector:
    app: linqh-mongo
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
      nodePort: 31002
  type: NodePort
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: linqh-mongo-pv
  labels:
    name: linqh-mongo-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  nfs:
    path: /nfsdata/mongo/db
    server: 192.168.99.90
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: linqh-mongo-pvc
  namespace: default
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: linqh-mongo
  labels:
    app: linqh-mongo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: linqh-mongo
  template:
    metadata:
      labels:
        app: linqh-mongo
    spec:
      containers:
        - name: linqh-mongo
          image: mongo:4.2
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: linqh-mongo-vol
              mountPath: /data/db/
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              value: root
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: linqh-mongo-auth
                  key: password
      volumes:
        - name: linqh-mongo-vol
          persistentVolumeClaim:
            claimName: linqh-mongo-pvc